# Schema for the Slick views style plugins.

views.style.slick:
  type: slick_extended
  label: 'Slick carousel'
  mapping:
    id:
      type: string
      label: 'Slick ID'
    thumbnail:
      type: string
      label: 'Thumbnail image'
