<?php

/**
 * @file
 * Slick carousel integration, the last carousel you'll ever need.
 */

/**
 * Implements hook_theme().
 */
function slick_theme() {
  $themes = [];
  $items  = ['slick', 'slide', 'grid', 'image', 'media', 'thumbnail', 'vanilla', 'wrapper'];
  foreach ($items as $item) {
    $key = $item == 'slick' ? $item : 'slick_' . $item;
    $themes[$key] = [
      'render element' => 'element',
      'file' => 'templates/slick.theme.inc',
    ];
  }
  return $themes;
}

/**
 * Implements hook_library_info_build().
 */
function slick_library_info_build() {
  $libraries['slick.css'] = [
    'dependencies' => ['slick/slick'],
    'css' => [
      'theme' => ['/libraries/slick/slick/slick-theme.css' => []],
    ],
  ];

  foreach (\Drupal::service('slick.manager')->getAvailableSkins() as $group => $skins) {
    foreach ($skins as $key => $skin) {
      $provider = isset($skin['provider']) ? $skin['provider'] : 'slick';
      $id = $provider . '.' . $group . '.' . $key;
      if (isset($skin['css']) && is_array($skin['css'])) {
        $libraries[$id]['css'] = $skin['css'];
      }
      if (isset($skin['js']) && is_array($skin['js'])) {
        $libraries[$id]['js'] = $skin['js'];
      }
    }
  }
  return $libraries;
}

/**
 * Implements hook_hook_info().
 *
 * @deprecated, will be removed anytime when a core solution is available.
 *
 * @see https://drupal.org/node/2233261
 */
function slick_hook_info() {
  $hooks['slick_skins_info'] = ['group' => 'slick'];
  return $hooks;
}
