<?php

/**
 * @file
 * Provides Slick carousel examples.
 *
 * Provides samples for Optionsets, Image styles, Views blocks and a few
 * supported alters.
 * Please do not use this module for your works, instead use it to learn how to
 * make the most out of Slick module. This module will be updated at times to
 * reflect the best shot Slick can give, so it may not keep your particular use.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_slick_skins_info().
 *
 * To provide own skins, simply provide the legit class namespace, and the class
 * must implement \Drupal\slick\SlickSkinInterface.
 *
 * @see slick.api.php for mode detailed instruction on this.
 * @see \Drupal\slick\SlickSkinInterface
 */
function slick_example_slick_skins_info() {
  return '\Drupal\slick_example\SlickExampleSkin';
}

/**
 * Implements hook_slick_attach_info_alter().
 *
 * Override slick assests before being processed.
 *
 * @param array $attach
 *   The associative array of attach information from SlickManager::attach().
 *
 * @see SlickManager::attach()
 */
function slick_example_slick_attach_info_alter(array &$attach) {
  // There is also UI option at: /admin/config/media/slick/ui.
  // Disable core Slick CSS: /libraries/slick/slick/slick-theme.css
  // $attach['slick_css'] = FALSE;
  // Disable module CSS: slick/css/theme/slick.theme.css
  // $attach['module_css'] = FALSE;
}

/**
 * Implements hook_help().
 */
function slick_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.slick_example':
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}
